# Model arguments
model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
tokenizer_name_or_path: meta-llama/Llama-3.2-1B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrachat_200k: 1.0
  HuggingFaceTB/self-oss-instruct-sc2-H4: 1.0
  HuggingFaceTB/OpenHermes-2.5-H4: 1.0
  HuggingFaceTB/everyday-conversations-llama3.1-2k: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: Llama-3.2-1B-sft-pruned
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 5
output_dir: output/Llama-3.2-1B-sft-pruned
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "epoch"
save_total_limit: 10
seed: 42
use_cache: false
warmup_ratio: 0.1
