# Model arguments
model_name_or_path: Mistral-Nemo-Minitron-2B-128k-Instruct
tokenizer_name_or_path: Mistral-Nemo-Minitron-2B-128k-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  medbench/wo_analysis: 1.0
dataset_splits:
- train
- test
dataset_configs:
  default:
    path: json
    data_files:
      train: train/*.json
      test: valid/*.json
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: Mistral-Nemo-Minitron-2B-128k-Instruct-custom
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 5
output_dir: output/Minitron-2B-sft-custom
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
push_to_hub: false
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: "epoch"
save_total_limit: 10
seed: 42
warmup_ratio: 0.1
