tag:
  - medbench
task: wo_analysis
task_alias: wo_analysis
dataset_path: wo_analysis  # Change this!
dataset_name: null
training_split: null
validation_split: null
test_split: test
doc_to_text: !function preprocess.doc_to_text
doc_to_target: !function preprocess.doc_to_target
process_results: !function preprocess.process_results
generation_kwargs:
  max_gen_toks: 32
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
