tag:
  - medbench
task: w_analysis
task_alias: w_analysis
dataset_path: w_analysis  # Change this!
dataset_name: null
training_split: null
validation_split: null
test_split: test
doc_to_text: !function preprocess.doc_to_text
doc_to_target: !function preprocess.doc_to_target
process_results: !function preprocess.process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
